# Pre-commit hooks configuration for retainr
# See https://pre-commit.com for more information
# These hooks match the CI pipeline checks exactly

repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: '.*\.md$'
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']

  # Python code formatting with Black (matches CI: black --check --diff .)
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.9

  # Python linting with Ruff (matches CI: ruff check .)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  # Python type checking with MyPy (matches CI: mypy mcp_server cli --ignore-missing-imports)
  # Disabled for now due to type annotation issues - CI will catch these
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.16.1
  #   hooks:
  #     - id: mypy
  #       args: [--ignore-missing-imports]
  #       files: ^(mcp_server|cli)/.*\.py$
  #       additional_dependencies:
  #         - fastapi
  #         - pydantic
  #         - click
  #         - httpx

# Configuration for individual hooks
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
