version: '3.8'

services:
  retainr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: retainr-server
    ports:
      - "8000:8000"
    volumes:
      # User-configurable memory storage (browsable markdown files)
      - ${RETAINR_MEMORY_DIR:-./memory}:/app/memory
      # Mount source code for development
      - ./mcp_server:/app/mcp_server
      - ./cli:/app/cli
    environment:
      - RETAINR_HOST=0.0.0.0
      - RETAINR_PORT=8000
      - RETAINR_MEMORY_DIR=/app/memory
      - RETAINR_CHROMA_HOST=chroma
      - RETAINR_CHROMA_PORT=8000
    env_file:
      - .env
    depends_on:
      - chroma
    restart: unless-stopped
    command: ["python", "-m", "uvicorn", "mcp_server.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  chroma:
    image: chromadb/chroma:latest
    container_name: retainr-chroma
    ports:
      - "8001:8000"  # Expose on 8001 for debugging (optional)
    volumes:
      - retainr_chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=FALSE
    restart: unless-stopped

volumes:
  retainr_chroma_data:
    driver: local
