name: 'Setup Python with Advanced Caching'
description: 'Complete Python setup with pip, ML models, and dependency caching'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'
  install-deps:
    description: 'Whether to install dependencies'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Set up Python with built-in pip caching
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'

    - name: Cache ML models (sentence-transformers)
      uses: actions/cache@v4
      with:
        path: ~/.cache/huggingface
        key: ${{ runner.os }}-models-${{ hashFiles('mcp_server/config.py') }}
        restore-keys: |
          ${{ runner.os }}-models-

    - name: Install dependencies
      if: inputs.install-deps == 'true'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
