name: Security Scan

on:
  pull_request:
    branches: [ main ]
  schedule:
    # Run weekly security scans on main branch
    - cron: '0 0 * * 0'
  # Note: Simple workflow - short-lived feature branches → main

jobs:
  security-scan:
    name: Security Analysis
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python with caching
      uses: ./.github/actions/setup-python
      with:
        install-deps: 'false'

    - name: Install security tools
      run: pip install bandit safety semgrep

    - name: Run Bandit security scan
      run: |
        bandit -r mcp_server -f json -o bandit-report.json || true
        bandit -r mcp_server

    - name: Run Safety dependency check
      run: |
        safety check --json --output safety-report.json || true
        safety check

    - name: Run Semgrep security scan
      run: |
        semgrep --config=auto mcp_server --json -o semgrep-report.json || true
        semgrep --config=auto mcp_server

    - name: Upload security scan results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          bandit-report.json
          safety-report.json
          semgrep-report.json
        retention-days: 30

  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"
